name: flutter_shutterstock_infinite_list
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  cached_network_image: ^3.0.0
  http: ^0.13.3
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  mockito: ^5.0.7

flutter:
  uses-material-design: true
